import type { Metadata } from "next";

import { cookies } from 'next/headers'; 
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
 // นำเข้า Client Component สำหรับปุ่มสลับภาษา
 
import { kanit } from "@/lib/fonts";
import clsx from 'clsx';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mini POS",
  description: "Generated by MAD Monkey Gangster",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const lngCookie = cookieStore.get('lng');
  const initialLocale = lngCookie ? lngCookie.value : 'th'; // ค่าเริ่มต้นเป็น 'en'
 
  const isRTL = initialLocale === 'ar';
  return (
    <html lang={initialLocale}>
      <body
        
        className={clsx(
          kanit.className,
          geistSans.variable,
          geistMono.variable,
          'antialiased relative min-h-screen',
          isRTL && 'rtl'
        )}
      >
      
   
        {children}
        <Toaster />
      </body>
    </html>
  );
}

 
